spring:
  application:
    name: ${SPRING_APP_NAME:EasyBank}

logging:
  pattern:
    console: ${LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){cyan} %clr(%-5level){magenta} %clr(%logger{36}){blue} - %msg%n}
