spring:
  application:
    name: ${SPRING_APP_NAME:EasyBank}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/easybank}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  pattern:
    console: ${LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){cyan} %clr(%-5level){magenta} %clr(%logger{36}){blue} - %msg%n}
